// Lista completa de personajes de Smash Ultimate
// id  → slug para Redis y URLs (sin espacios ni caracteres especiales)
// img → ruta relativa al archivo en /public/images/characters/

export const CHARACTERS = [
  { id: 'banjo-kazooie',   name: 'Banjo & Kazooie',   img: 'Banjo Kazooie.png'    },
  { id: 'bayonetta',       name: 'Bayonetta',          img: 'Bayonetta.png'        },
  { id: 'bowser-jr',       name: 'Bowser Jr.',         img: 'Bowser Jr.png'        },
  { id: 'bowser',          name: 'Bowser',             img: 'Bowser.png'           },
  { id: 'byleth',          name: 'Byleth',             img: 'Byleth.png'           },
  { id: 'captain-falcon',  name: 'Captain Falcon',     img: 'Captain Falcon.png'   },
  { id: 'chrom',           name: 'Chrom',              img: 'Chrom.png'            },
  { id: 'cloud',           name: 'Cloud',              img: 'Cloud.png'            },
  { id: 'corrin',          name: 'Corrin',             img: 'Corrin.png'           },
  { id: 'daisy',           name: 'Daisy',              img: 'Daisy.png'            },
  { id: 'dark-pit',        name: 'Dark Pit',           img: 'Dark Pit.png'         },
  { id: 'dark-samus',      name: 'Dark Samus',         img: 'Dark Samus.png'       },
  { id: 'diddy-kong',      name: 'Diddy Kong',         img: 'Diddy Kong.png'       },
  { id: 'donkey-kong',     name: 'Donkey Kong',        img: 'Donkey Kong.png'      },
  { id: 'dr-mario',        name: 'Dr. Mario',          img: 'Dr. Mario.png'        },
  { id: 'duck-hunt',       name: 'Duck Hunt',          img: 'Duck Hunt.png'        },
  { id: 'falco',           name: 'Falco',              img: 'Falco.png'            },
  { id: 'fox',             name: 'Fox',                img: 'Fox.png'              },
  { id: 'ganondorf',       name: 'Ganondorf',          img: 'Ganondorf.png'        },
  { id: 'greninja',        name: 'Greninja',           img: 'Greninja.png'         },
  { id: 'hero',            name: 'Hero',               img: 'Hero.png'             },
  { id: 'ice-climbers',    name: 'Ice Climbers',       img: 'Ice Climbers.png'     },
  { id: 'ike',             name: 'Ike',                img: 'Ike.png'             },
  { id: 'incineroar',      name: 'Incineroar',         img: 'Incineroar.png'       },
  { id: 'inkling',         name: 'Inkling',            img: 'Inkling.png'          },
  { id: 'isabelle',        name: 'Isabelle',           img: 'Isabelle.png'         },
  { id: 'jigglypuff',      name: 'Jigglypuff',         img: 'Jigglypuff.png'       },
  { id: 'joker',           name: 'Joker',              img: 'Joker.png'            },
  { id: 'kazuya',          name: 'Kazuya',             img: 'Kazuya.png'           },
  { id: 'ken',             name: 'Ken',                img: 'Ken.png'              },
  { id: 'king-dedede',     name: 'King Dedede',        img: 'King Dedede.png'      },
  { id: 'king-k-rool',     name: 'King K. Rool',       img: 'King K. Rool.png'     },
  { id: 'kirby',           name: 'Kirby',              img: 'Kirby.png'            },
  { id: 'link',            name: 'Link',               img: 'Link.png'             },
  { id: 'little-mac',      name: 'Little Mac',         img: 'Little Mac.png'       },
  { id: 'lucario',         name: 'Lucario',            img: 'Lucario.png'          },
  { id: 'lucas',           name: 'Lucas',              img: 'Lucas.png'            },
  { id: 'lucina',          name: 'Lucina',             img: 'Lucina.png'           },
  { id: 'luigi',           name: 'Luigi',              img: 'Luigi.png'            },
  { id: 'mario',           name: 'Mario',              img: 'Mario.png'            },
  { id: 'marth',           name: 'Marth',              img: 'Marth.png'            },
  { id: 'mega-man',        name: 'Mega Man',           img: 'Mega Man.png'         },
  { id: 'meta-knight',     name: 'Meta Knight',        img: 'Meta Knight.png'      },
  { id: 'mewtwo',          name: 'Mewtwo',             img: 'Mewtwo.png'           },
  { id: 'mii-brawler',     name: 'Mii Brawler',        img: 'Mii Brawler.png'      },
  { id: 'mii-gunner',      name: 'Mii Gunner',         img: 'Mii Gunner.png'       },
  { id: 'mii-swordfighter',name: 'Mii Swordfighter',   img: 'Mii Swordfighter.png' },
  { id: 'min-min',         name: 'Min Min',            img: 'Min Min.png'          },
  { id: 'mr-game-watch',   name: 'Mr. Game & Watch',   img: 'Mr. Game & Watch.png' },
  { id: 'ness',            name: 'Ness',               img: 'Ness.png'             },
  { id: 'olimar',          name: 'Olimar',             img: 'Olimar.png'           },
  { id: 'pac-man',         name: 'Pac-Man',            img: 'Pac-Man.png'          },
  { id: 'palutena',        name: 'Palutena',           img: 'Palutena.png'         },
  { id: 'peach',           name: 'Peach',              img: 'Peach.png'            },
  { id: 'pichu',           name: 'Pichu',              img: 'Pichu.png'            },
  { id: 'pikachu',         name: 'Pikachu',            img: 'Pikachu.png'          },
  { id: 'piranha-plant',   name: 'Piranha Plant',      img: 'Piranha Plant.png'    },
  { id: 'pit',             name: 'Pit',                img: 'Pit.png'              },
  { id: 'pokemon-trainer', name: 'Pokémon Trainer',    img: 'Pokemon Trainer.png'  },
  { id: 'pyra-mythra',     name: 'Pyra / Mythra',      img: 'Pyra Mythra.png'      },
  { id: 'rob',             name: 'R.O.B.',             img: 'R.O.B.png'            },
  { id: 'richter',         name: 'Richter',            img: 'Richter.png'          },
  { id: 'ridley',          name: 'Ridley',             img: 'Ridley.png'           },
  { id: 'robin',           name: 'Robin',              img: 'Robin.png'            },
  { id: 'rosalina-luma',   name: 'Rosalina & Luma',    img: 'Rosalina & Luma.png'  },
  { id: 'roy',             name: 'Roy',                img: 'Roy.png'              },
  { id: 'ryu',             name: 'Ryu',                img: 'Ryu.png'              },
  { id: 'samus',           name: 'Samus',              img: 'Samus.png'            },
  { id: 'sephiroth',       name: 'Sephiroth',          img: 'Sephiroth.png'        },
  { id: 'sheik',           name: 'Sheik',              img: 'Sheik.png'            },
  { id: 'shulk',           name: 'Shulk',              img: 'Shulk.png'            },
  { id: 'simon',           name: 'Simon',              img: 'Simon.png'            },
  { id: 'snake',           name: 'Snake',              img: 'Snake.png'            },
  { id: 'sonic',           name: 'Sonic',              img: 'Sonic.png'            },
  { id: 'sora',            name: 'Sora',               img: 'Sora.png'             },
  { id: 'steve',           name: 'Steve',              img: 'Steve.png'            },
  { id: 'terry',           name: 'Terry',              img: 'Terry.png'            },
  { id: 'toon-link',       name: 'Toon Link',          img: 'Toon Link.png'        },
  { id: 'villager',        name: 'Villager',           img: 'Villager.png'         },
  { id: 'wario',           name: 'Wario',              img: 'Wario.png'            },
  { id: 'wii-fit-trainer', name: 'Wii Fit Trainer',    img: 'Wii Fit Trainer.png'  },
  { id: 'wolf',            name: 'Wolf',               img: 'Wolf.png'             },
  { id: 'yoshi',           name: 'Yoshi',              img: 'Yoshi.png'            },
  { id: 'young-link',      name: 'Young Link',         img: 'Young Link.png'       },
  { id: 'zelda',           name: 'Zelda',              img: 'Zelda.png'            },
  { id: 'zero-suit-samus', name: 'Zero Suit Samus',    img: 'Zero Suit Samus.png'  },
];

/** Devuelve el objeto de personaje por su id */
export function getCharById(id) {
  return CHARACTERS.find(c => c.id === id) || null;
}

/** Ruta pública de la imagen de un personaje */
export function charImgPath(img) {
  return `/images/characters/${encodeURIComponent(img)}`;
}
