// Lista completa de personajes de Smash Ultimate
// id  → slug para Redis y URLs (sin espacios ni caracteres especiales)
// img → ruta relativa al archivo en /public/images/characters/

export const CHARACTERS = [
  { id: 'banjo-kazooie',   name: 'Banjo & Kazooie',   img: 'Banjo Kazooie.png'    },
  { id: 'bayonetta',       name: 'Bayonetta',          img: 'Bayonetta.png'        },
  { id: 'bowser-jr',       name: 'Bowser Jr.',         img: 'Bowser Jr.png'        },
  { id: 'bowser',          name: 'Bowser',             img: 'Bowser.png'           },
  { id: 'byleth',          name: 'Byleth',             img: 'Byleth.png'           },
  { id: 'captain-falcon',  name: 'Captain Falcon',     img: 'Captain Falcon.png'   },
  { id: 'chrom',           name: 'Chrom',              img: 'Chrom.png'            },
  { id: 'cloud',           name: 'Cloud',              img: 'Cloud.png'            },
  { id: 'corrin',          name: 'Corrin',             img: 'Corrin.png'           },
  { id: 'daisy',           name: 'Daisy',              img: 'Daisy.png'            },
  { id: 'dark-pit',        name: 'Dark Pit',           img: 'Dark Pit.png'         },
  { id: 'dark-samus',      name: 'Dark Samus',         img: 'Dark Samus.png'       },
  { id: 'diddy-kong',      name: 'Diddy Kong',         img: 'Diddy Kong.png'       },
  { id: 'donkey-kong',     name: 'Donkey Kong',        img: 'Donkey Kong.png'      },
  { id: 'dr-mario',        name: 'Dr. Mario',          img: 'Dr. Mario.png'        },
  { id: 'duck-hunt',       name: 'Duck Hunt',          img: 'Duck Hunt.png'        },
  { id: 'falco',           name: 'Falco',              img: 'Falco.png'            },
  { id: 'fox',             name: 'Fox',                img: 'Fox.png'              },
  { id: 'ganondorf',       name: 'Ganondorf',          img: 'Ganondorf.png'        },
  { id: 'greninja',        name: 'Greninja',           img: 'Greninja.png'         },
  { id: 'hero',            name: 'Hero',               img: 'Hero.png'             },
  { id: 'ice-climbers',    name: 'Ice Climbers',       img: 'Ice Climbers.png'     },
  { id: 'ike',             name: 'Ike',                img: 'Ike.png'             },
  { id: 'incineroar',      name: 'Incineroar',         img: 'Incineroar.png'       },
  { id: 'inkling',         name: 'Inkling',            img: 'Inkling.png'          },
  { id: 'isabelle',        name: 'Isabelle',           img: 'Isabelle.png'         },
  { id: 'jigglypuff',      name: 'Jigglypuff',         img: 'Jigglypuff.png'       },
  { id: 'joker',           name: 'Joker',              img: 'Joker.png'            },
  { id: 'kazuya',          name: 'Kazuya',             img: 'Kazuya.png'           },
  { id: 'ken',             name: 'Ken',                img: 'Ken.png'              },
  { id: 'king-dedede',     name: 'King Dedede',        img: 'King Dedede.png'      },
  { id: 'king-k-rool',     name: 'King K. Rool',       img: 'King K. Rool.png'     },
  { id: 'kirby',           name: 'Kirby',              img: 'Kirby.png'            },
  { id: 'link',            name: 'Link',               img: 'Link.png'             },
  { id: 'little-mac',      name: 'Little Mac',         img: 'Little Mac.png'       },
  { id: 'lucario',         name: 'Lucario',            img: 'Lucario.png'          },
  { id: 'lucas',           name: 'Lucas',              img: 'Lucas.png'            },
  { id: 'lucina',          name: 'Lucina',             img: 'Lucina.png'           },
  { id: 'luigi',           name: 'Luigi',              img: 'Luigi.png'            },
  { id: 'mario',           name: 'Mario',              img: 'Mario.png'            },
  { id: 'marth',           name: 'Marth',              img: 'Marth.png'            },
  { id: 'mega-man',        name: 'Mega Man',           img: 'Mega Man.png'         },
  { id: 'meta-knight',     name: 'Meta Knight',        img: 'Meta Knight.png'      },
  { id: 'mewtwo',          name: 'Mewtwo',             img: 'Mewtwo.png'           },
  { id: 'mii-brawler',     name: 'Mii Brawler',        img: 'Mii Brawler.png'      },
  { id: 'mii-gunner',      name: 'Mii Gunner',         img: 'Mii Gunner.png'       },
  { id: 'mii-swordfighter',name: 'Mii Swordfighter',   img: 'Mii Swordfighter.png' },
  { id: 'min-min',         name: 'Min Min',            img: 'Min Min.png'          },
  { id: 'mr-game-watch',   name: 'Mr. Game & Watch',   img: 'Mr. Game & Watch.png' },
  { id: 'ness',            name: 'Ness',               img: 'Ness.png'             },
  { id: 'olimar',          name: 'Olimar',             img: 'Olimar.png'           },
  { id: 'pac-man',         name: 'Pac-Man',            img: 'Pac-Man.png'          },
  { id: 'palutena',        name: 'Palutena',           img: 'Palutena.png'         },
  { id: 'peach',           name: 'Peach',              img: 'Peach.png'            },
  { id: 'pichu',           name: 'Pichu',              img: 'Pichu.png'            },
  { id: 'pikachu',         name: 'Pikachu',            img: 'Pikachu.png'          },
  { id: 'piranha-plant',   name: 'Piranha Plant',      img: 'Piranha Plant.png'    },
  { id: 'pit',             name: 'Pit',                img: 'Pit.png'              },
  { id: 'pokemon-trainer', name: 'Pokémon Trainer',    img: 'Pokemon Trainer.png'  },
  { id: 'pyra-mythra',     name: 'Pyra / Mythra',      img: 'Pyra Mythra.png'      },
  { id: 'rob',             name: 'R.O.B.',             img: 'R.O.B.png'            },
  { id: 'richter',         name: 'Richter',            img: 'Richter.png'          },
  { id: 'ridley',          name: 'Ridley',             img: 'Ridley.png'           },
  { id: 'robin',           name: 'Robin',              img: 'Robin.png'            },
  { id: 'rosalina-luma',   name: 'Rosalina & Luma',    img: 'Rosalina & Luma.png'  },
  { id: 'roy',             name: 'Roy',                img: 'Roy.png'              },
  { id: 'ryu',             name: 'Ryu',                img: 'Ryu.png'              },
  { id: 'samus',           name: 'Samus',              img: 'Samus.png'            },
  { id: 'sephiroth',       name: 'Sephiroth',          img: 'Sephiroth.png'        },
  { id: 'sheik',           name: 'Sheik',              img: 'Sheik.png'            },
  { id: 'shulk',           name: 'Shulk',              img: 'Shulk.png'            },
  { id: 'simon',           name: 'Simon',              img: 'Simon.png'            },
  { id: 'snake',           name: 'Snake',              img: 'Snake.png'            },
  { id: 'sonic',           name: 'Sonic',              img: 'Sonic.png'            },
  { id: 'sora',            name: 'Sora',               img: 'Sora.png'             },
  { id: 'steve',           name: 'Steve',              img: 'Steve.png'            },
  { id: 'terry',           name: 'Terry',              img: 'Terry.png'            },
  { id: 'toon-link',       name: 'Toon Link',          img: 'Toon Link.png'        },
  { id: 'villager',        name: 'Villager',           img: 'Villager.png'         },
  { id: 'wario',           name: 'Wario',              img: 'Wario.png'            },
  { id: 'wii-fit-trainer', name: 'Wii Fit Trainer',    img: 'Wii Fit Trainer.png'  },
  { id: 'wolf',            name: 'Wolf',               img: 'Wolf.png'             },
  { id: 'yoshi',           name: 'Yoshi',              img: 'Yoshi.png'            },
  { id: 'young-link',      name: 'Young Link',         img: 'Young Link.png'       },
  { id: 'zelda',           name: 'Zelda',              img: 'Zelda.png'            },
  { id: 'zero-suit-samus', name: 'Zero Suit Samus',    img: 'Zero Suit Samus.png'  },
];

/** Devuelve el objeto de personaje por su id */
export function getCharById(id) {
  return CHARACTERS.find(c => c.id === id) || null;
}

/** Ruta pública de la imagen de un personaje */
export function charImgPath(img) {
  return `/images/characters/${encodeURIComponent(img)}`;
}

/** Map de character ID → nombre de archivo de render (carpeta /images/Render SSBU/) */
export const CHARACTER_RENDERS = {
  'banjo-kazooie':    'Banjo Render SSBU.png',
  'bayonetta':        'Bayonetta.png',
  'bowser-jr':        'Bowser Jr..png',
  'bowser':           'Bowser.png',
  'byleth':           'Byleth.png',
  'captain-falcon':   'Captain Falcon.png',
  'chrom':            'Chrom.png',
  'cloud':            'Cloud.png',
  'corrin':           'Corrin.png',
  'daisy':            'Daisy.png',
  'dark-pit':         'Dark Pit.png',
  'dark-samus':       'Dark Samus.png',
  'diddy-kong':       'Diddy Kong.png',
  'donkey-kong':      'Donkey Kong.png',
  'dr-mario':         'Dr. Mario.png',
  'duck-hunt':        'Duck Hunt.png',
  'falco':            'Falco.png',
  'fox':              'Fox.png',
  'ganondorf':        'Ganondorf.png',
  'greninja':         'Greninja.png',
  'hero':             'Hero.png',
  'ice-climbers':     'Ice Climbers.png',
  'ike':              'Ike.png',
  'incineroar':       'Incineroar.png',
  'inkling':          'Inkling.png',
  'isabelle':         'Isabelle.png',
  'jigglypuff':       'Jiggly.png',
  'joker':            'Joker.png',
  'kazuya':           'Kazuya.png',
  'ken':              'Ken.png',
  'king-dedede':      'King Dedede.png',
  'king-k-rool':      'King K. Rool.png',
  'kirby':            'Kirby.png',
  'link':             'Link.png',
  'little-mac':       'Little Mac.png',
  'lucario':          'Lucario.png',
  'lucas':            'Lucas.png',
  'luigi':            'Luigi.png',
  'mario':            'Mario.png',
  'marth':            'Marth.png',
  'mega-man':         'Megaman.png',
  'meta-knight':      'Meta Knight.png',
  'mewtwo':           'Mewtoo.png',
  'mii-brawler':      'Mii Brawler.png',
  'mii-swordfighter': 'Mii Swordfighter.png',
  'min-min':          'Min Min.png',
  'mr-game-watch':    'Mr. Game & Watch.png',
  'ness':             'Ness.png',
  'olimar':           'Olimar.png',
  'pac-man':          'Pacman.png',
  'palutena':         'Palutena.png',
  'peach':            'Peach.png',
  'pikachu':          'Pikachu.png',
  'piranha-plant':    'Piranha Plant.png',
  'pit':              'Pit.png',
  'pokemon-trainer':  'Pokemon Trainer.png',
  'pyra-mythra':      'Pyra & Mythra.png',
  'rob':              'R.O.B..png',
  'ridley':           'Ridley.png',
  'robin':            'Robin.png',
  'rosalina-luma':    'Rosalina.png',
  'roy':              'Roy.png',
  'ryu':              'Ryu.png',
  'samus':            'Samus.png',
  'sephiroth':         'Sephiroth.png',
  'sheik':            'Sheik.png',
  'shulk':            'Shulk.png',
  'simon':            'Simon Belmont.png',
  'snake':            'Snake.png',
  'sonic':            'Sonic.png',
  'sora':             'Sora.png',
  'steve':            'Steve.png',
  'terry':            'Terry.png',
  'toon-link':        'Toon Link.png',
  'villager':         'Villager.png',
  'wario':            'Wario.png',
  'wii-fit-trainer':  'Wii fit trainer.png',
  'wolf':             'Wolf.png',
  'yoshi':            'Yoshi.png',
  'young-link':       'Link ni\u00f1o.png',
  'zelda':            'Zelda.png',
  'zero-suit-samus':  'Zero Suit Samus.png',
};

/** Ruta pública del render de un personaje (carpeta con espacio en el nombre) */
export function charRenderPath(renderFile) {
  return `/images/Render%20SSBU/${encodeURIComponent(renderFile)}`;
}

/** Mapa de Start.GG character selection IDs → nuestro character id local */
export const STARTGG_CHAR_MAP = {
  1271: 'mario', 1272: 'donkey-kong', 1273: 'link', 1274: 'samus',
  1275: 'dark-samus', 1276: 'yoshi', 1277: 'kirby', 1278: 'fox',
  1279: 'pikachu', 1280: 'luigi', 1281: 'ness', 1282: 'captain-falcon',
  1283: 'jigglypuff', 1285: 'peach', 1286: 'daisy', 1284: 'bowser',
  1287: 'ice-climbers', 1288: 'sheik', 1289: 'zelda', 1290: 'dr-mario',
  1291: 'pichu', 1292: 'falco', 1293: 'marth', 1294: 'lucina',
  1295: 'young-link', 1296: 'ganondorf', 1297: 'mewtwo', 1298: 'roy',
  1299: 'chrom', 1300: 'mr-game-watch', 1301: 'meta-knight', 1302: 'pit',
  1303: 'dark-pit', 1304: 'zero-suit-samus', 1305: 'wario', 1306: 'snake',
  1307: 'ike', 1308: 'pokemon-trainer', 1309: 'diddy-kong', 1310: 'lucas',
  1311: 'sonic', 1312: 'king-dedede', 1313: 'olimar', 1314: 'lucario',
  1315: 'rob', 1316: 'toon-link', 1317: 'wolf', 1318: 'villager',
  1319: 'mega-man', 1320: 'wii-fit-trainer', 1321: 'rosalina-luma',
  1322: 'little-mac', 1323: 'greninja', 1324: 'palutena', 1325: 'pac-man',
  1326: 'robin', 1327: 'shulk', 1328: 'bowser-jr', 1329: 'duck-hunt',
  1330: 'ryu', 1331: 'ken', 1332: 'cloud', 1333: 'corrin',
  1334: 'bayonetta', 1335: 'inkling', 1336: 'ridley', 1337: 'simon',
  1338: 'richter', 1339: 'king-k-rool', 1340: 'isabelle', 1341: 'incineroar',
  1342: 'mii-brawler', 1343: 'mii-swordfighter', 1344: 'mii-gunner',
  1345: 'piranha-plant', 1346: 'joker', 1347: 'hero', 1348: 'banjo-kazooie',
  1349: 'terry', 1350: 'byleth', 1351: 'min-min', 1352: 'steve',
  1353: 'sephiroth', 1354: 'pyra-mythra', 1355: 'kazuya', 1356: 'sora',
  // IDs alternativos de Start.GG (selectionValue puede diferir del character listing)
  1897: 'sora',
};
