// Constants para el sistema de baneos
export const STAGES_GAME1 = [
  { id: 'battlefield', name: 'Battlefield', image: '/images/stages/battlefield.png' },
  { id: 'small-battlefield', name: 'Small Battlefield', image: '/images/stages/small-battlefield.png' },
  { id: 'pokemon-stadium-2', name: 'Pokémon Stadium 2', image: '/images/stages/pokemon-stadium-2.png' },
  { id: 'smashville', name: 'Smashville', image: '/images/stages/smashville.png' },
  { id: 'town-and-city', name: 'Town and City', image: '/images/stages/town-and-city.png' },
];

export const STAGES_GAME2_PLUS = [
  { id: 'battlefield', name: 'Battlefield', image: '/images/stages/battlefield.png' },
  { id: 'small-battlefield', name: 'Small Battlefield', image: '/images/stages/small-battlefield.png' },
  { id: 'pokemon-stadium-2', name: 'Pokémon Stadium 2', image: '/images/stages/pokemon-stadium-2.png' },
  { id: 'smashville', name: 'Smashville', image: '/images/stages/smashville.png' },
  { id: 'town-and-city', name: 'Town and City', image: '/images/stages/town-and-city.png' },
  { id: 'hollow-bastion', name: 'Hollow Bastion', image: '/images/stages/hollow-bastion.png' },
  { id: 'final-destination', name: 'Final Destination', image: '/images/stages/final-destination.png' },
  { id: 'kalos', name: 'Kalos', image: '/images/stages/kalos.png' },
];

// Lista completa de personajes de Smash Ultimate (89 personajes)
export const CHARACTERS = [
  { id: 'mario', name: 'Mario', image: '/images/characters/mario.png' },
  { id: 'donkey-kong', name: 'Donkey Kong', image: '/images/characters/donkey-kong.png' },
  { id: 'link', name: 'Link', image: '/images/characters/link.png' },
  { id: 'samus', name: 'Samus', image: '/images/characters/samus.png' },
  { id: 'dark-samus', name: 'Dark Samus', image: '/images/characters/dark-samus.png' },
  { id: 'yoshi', name: 'Yoshi', image: '/images/characters/yoshi.png' },
  { id: 'kirby', name: 'Kirby', image: '/images/characters/kirby.png' },
  { id: 'fox', name: 'Fox', image: '/images/characters/fox.png' },
  { id: 'pikachu', name: 'Pikachu', image: '/images/characters/pikachu.png' },
  { id: 'luigi', name: 'Luigi', image: '/images/characters/luigi.png' },
  { id: 'ness', name: 'Ness', image: '/images/characters/ness.png' },
  { id: 'captain-falcon', name: 'Captain Falcon', image: '/images/characters/captain-falcon.png' },
  { id: 'jigglypuff', name: 'Jigglypuff', image: '/images/characters/jigglypuff.png' },
  { id: 'peach', name: 'Peach', image: '/images/characters/peach.png' },
  { id: 'daisy', name: 'Daisy', image: '/images/characters/daisy.png' },
  { id: 'bowser', name: 'Bowser', image: '/images/characters/bowser.png' },
  { id: 'ice-climbers', name: 'Ice Climbers', image: '/images/characters/ice-climbers.png' },
  { id: 'sheik', name: 'Sheik', image: '/images/characters/sheik.png' },
  { id: 'zelda', name: 'Zelda', image: '/images/characters/zelda.png' },
  { id: 'dr-mario', name: 'Dr. Mario', image: '/images/characters/dr-mario.png' },
  { id: 'pichu', name: 'Pichu', image: '/images/characters/pichu.png' },
  { id: 'falco', name: 'Falco', image: '/images/characters/falco.png' },
  { id: 'marth', name: 'Marth', image: '/images/characters/marth.png' },
  { id: 'lucina', name: 'Lucina', image: '/images/characters/lucina.png' },
  { id: 'young-link', name: 'Young Link', image: '/images/characters/young-link.png' },
  { id: 'ganondorf', name: 'Ganondorf', image: '/images/characters/ganondorf.png' },
  { id: 'mewtwo', name: 'Mewtwo', image: '/images/characters/mewtwo.png' },
  { id: 'roy', name: 'Roy', image: '/images/characters/roy.png' },
  { id: 'chrom', name: 'Chrom', image: '/images/characters/chrom.png' },
  { id: 'mr-game-and-watch', name: 'Mr. Game & Watch', image: '/images/characters/mr-game-and-watch.png' },
  { id: 'meta-knight', name: 'Meta Knight', image: '/images/characters/meta-knight.png' },
  { id: 'pit', name: 'Pit', image: '/images/characters/pit.png' },
  { id: 'dark-pit', name: 'Dark Pit', image: '/images/characters/dark-pit.png' },
  { id: 'zero-suit-samus', name: 'Zero Suit Samus', image: '/images/characters/zero-suit-samus.png' },
  { id: 'wario', name: 'Wario', image: '/images/characters/wario.png' },
  { id: 'snake', name: 'Snake', image: '/images/characters/snake.png' },
  { id: 'ike', name: 'Ike', image: '/images/characters/ike.png' },
  { id: 'pokemon-trainer', name: 'Pokémon Trainer', image: '/images/characters/pokemon-trainer.png' },
  { id: 'diddy-kong', name: 'Diddy Kong', image: '/images/characters/diddy-kong.png' },
  { id: 'lucas', name: 'Lucas', image: '/images/characters/lucas.png' },
  { id: 'sonic', name: 'Sonic', image: '/images/characters/sonic.png' },
  { id: 'king-dedede', name: 'King Dedede', image: '/images/characters/king-dedede.png' },
  { id: 'olimar', name: 'Olimar', image: '/images/characters/olimar.png' },
  { id: 'lucario', name: 'Lucario', image: '/images/characters/lucario.png' },
  { id: 'rob', name: 'R.O.B.', image: '/images/characters/rob.png' },
  { id: 'toon-link', name: 'Toon Link', image: '/images/characters/toon-link.png' },
  { id: 'wolf', name: 'Wolf', image: '/images/characters/wolf.png' },
  { id: 'villager', name: 'Villager', image: '/images/characters/villager.png' },
  { id: 'mega-man', name: 'Mega Man', image: '/images/characters/mega-man.png' },
  { id: 'wii-fit-trainer', name: 'Wii Fit Trainer', image: '/images/characters/wii-fit-trainer.png' },
  { id: 'rosalina', name: 'Rosalina & Luma', image: '/images/characters/rosalina.png' },
  { id: 'little-mac', name: 'Little Mac', image: '/images/characters/little-mac.png' },
  { id: 'greninja', name: 'Greninja', image: '/images/characters/greninja.png' },
  { id: 'palutena', name: 'Palutena', image: '/images/characters/palutena.png' },
  { id: 'pac-man', name: 'Pac-Man', image: '/images/characters/pac-man.png' },
  { id: 'robin', name: 'Robin', image: '/images/characters/robin.png' },
  { id: 'shulk', name: 'Shulk', image: '/images/characters/shulk.png' },
  { id: 'bowser-jr', name: 'Bowser Jr.', image: '/images/characters/bowser-jr.png' },
  { id: 'duck-hunt', name: 'Duck Hunt', image: '/images/characters/duck-hunt.png' },
  { id: 'ryu', name: 'Ryu', image: '/images/characters/ryu.png' },
  { id: 'ken', name: 'Ken', image: '/images/characters/ken.png' },
  { id: 'cloud', name: 'Cloud', image: '/images/characters/cloud.png' },
  { id: 'corrin', name: 'Corrin', image: '/images/characters/corrin.png' },
  { id: 'bayonetta', name: 'Bayonetta', image: '/images/characters/bayonetta.png' },
  { id: 'inkling', name: 'Inkling', image: '/images/characters/inkling.png' },
  { id: 'ridley', name: 'Ridley', image: '/images/characters/ridley.png' },
  { id: 'simon', name: 'Simon', image: '/images/characters/simon.png' },
  { id: 'richter', name: 'Richter', image: '/images/characters/richter.png' },
  { id: 'king-k-rool', name: 'King K. Rool', image: '/images/characters/king-k-rool.png' },
  { id: 'isabelle', name: 'Isabelle', image: '/images/characters/isabelle.png' },
  { id: 'incineroar', name: 'Incineroar', image: '/images/characters/incineroar.png' },
  { id: 'piranha-plant', name: 'Piranha Plant', image: '/images/characters/piranha-plant.png' },
  { id: 'joker', name: 'Joker', image: '/images/characters/joker.png' },
  { id: 'hero', name: 'Hero', image: '/images/characters/hero.png' },
  { id: 'banjo-kazooie', name: 'Banjo & Kazooie', image: '/images/characters/banjo-kazooie.png' },
  { id: 'terry', name: 'Terry', image: '/images/characters/terry.png' },
  { id: 'byleth', name: 'Byleth', image: '/images/characters/byleth.png' },
  { id: 'min-min', name: 'Min Min', image: '/images/characters/min-min.png' },
  { id: 'steve', name: 'Steve', image: '/images/characters/steve.png' },
  { id: 'sephiroth', name: 'Sephiroth', image: '/images/characters/sephiroth.png' },
  { id: 'pyra-mythra', name: 'Pyra/Mythra', image: '/images/characters/pyra-mythra.png' },
  { id: 'kazuya', name: 'Kazuya', image: '/images/characters/kazuya.png' },
  { id: 'sora', name: 'Sora', image: '/images/characters/sora.png' },
  { id: 'mii-brawler', name: 'Mii Brawler', image: '/images/characters/mii-brawler.png' },
  { id: 'mii-swordfighter', name: 'Mii Swordfighter', image: '/images/characters/mii-swordfighter.png' },
  { id: 'mii-gunner', name: 'Mii Gunner', image: '/images/characters/mii-gunner.png' },
];

export const PHASES = {
  RPS: 'RPS',
  STAGE_BAN: 'STAGE_BAN',
  STAGE_SELECT: 'STAGE_SELECT',
  CHARACTER_SELECT: 'CHARACTER_SELECT',
  PLAYING: 'PLAYING',
  FINISHED: 'FINISHED',
};

export const PHASE_NAMES = {
  RPS: 'Piedra, Papel o Tijera',
  STAGE_BAN: 'Baneo de Stages',
  STAGE_SELECT: 'Selección de Stage',
  CHARACTER_SELECT: 'Selección de Personajes',
  PLAYING: 'Jugando',
  FINISHED: 'Serie Finalizada',
};

export const getStageData = (stageId) => {
  const allStages = [...STAGES_GAME1, ...STAGES_GAME2_PLUS];
  return allStages.find(stage => stage.id === stageId);
};

export const getCharacterData = (characterId) => {
  return CHARACTERS.find(char => char.id === characterId);
};
